[Settings]
; If your prefer other themes variant, replace the "rose-pine-gtk" with "rose-pine-moon-gtk" or "rose-pine-dawn-gtk"
gtk-theme-name=rose-pine-dawn-gtk

; If you prefer other icons variant, replace the "rose-pine-icons" with "rose-pine-moon-icons" or "rose-pine-dawn-icons"
gtk-icon-theme-name=rose-pine-dawn-icons
