preload = ~/dotfiles/wallpapers/a_group_of_buildings_with_a_moon_in_the_sky.png
# wallpaper =  ~/dotfiles/wallpapers/a_group_of_buildings_with_a_moon_in_the_sky.png

wallpaper {
    monitor = eDP-1
    path = $HOME/dotfiles/wallpapers/a_group_of_buildings_with_a_moon_in_the_sky.png
    fit_mode = cover
}
