[appearance]

font_name = "DepartureMono Nerd Font"
style = "Solid"

success_color = "#56949f"
text_color = "#575279"

workspace_colors = [ "#f2e9e1", "#e0def4", "#c4a7e7" ]

[appearance.primary_color]
base = "#faf4ed"
text = "#575279"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f6c177"

[appearance.background_color]
base = "#faf4ed"
weak = "#fffaf3"
strong = "#f2e9e1"

[appearance.secondary_color]
base = "#fffaf3"
